export { default as api, apiClient } from "./client";
export * from "./auth";
export * from "./departments";
export * from "./blocks";
export * from "./events";
export * from "./admins";
export * from "./courses";
export * from "./users";
export * from "./roles";
export * from "./yearLevels";
export * from "./eventNames";
export * from "./schoolYears";
export * from "./attendance";